import { Type } from "typebox";

import {
  AgentParams,
  AgentProvisioningParams,
  PresetParams,
  CreatePresetBody,
  UpdatePresetBody,
  AgentRuntimeCredentialsBody,
  ConfigurationParams,
  CreateIAMAccessBindingBody,
  CreateIAMRoleBody,
  CreateAgentBody,
  DiscoverAgentModelsBody,
  DiscoverAgentPluginsBody,
  DiscoverAgentPluginDetailsBody,
  DiscoverSavedAgentPluginsBody,
  DiscoverSavedAgentPluginDetailsBody,
  CreateConfigurationBody,
  CreateNamespaceBody,
  ProvisionAgentBody,
  CreateSecretBody,
  CreateServiceAccountBody,
  CreateServiceAccountCredentialBody,
  DeploymentParams,
  EmptyQuery,
  IAMAccessBindingParams,
  IAMRoleParams,
  NamedResourceBody,
  NamespaceParams,
  RevisionParams,
  SecretParams,
  ServiceAccountParams,
  UpdateAgentBody,
  UpdateConfigurationBody,
  UpdateSecretBody,
  UpdateServiceAccountCredentialBody,
  UpdateWorkspaceFileBody,
  WorkspaceFileParams,
} from "./common.ts";
import {
  AgentListResponse,
  AgentModelListResponse,
  AgentPluginCatalogResponse,
  AgentPluginDetailsResponse,
  AgentPluginPolicyCapabilitiesResponse,
  PresetResponse,
  PresetListResponse,
  AgentDeploymentStatusResponse,
  AgentDeploymentDiagnosticsResponse,
  AgentProvisioningResponse,
  AgentProvisioningStatusResponse,
  AgentRuntimeCredentialResponse,
  AgentRuntimeImagesResponse,
  AgentResponse,
  AgentRevisionListResponse,
  AgentRevisionResponse,
  ConfigurationResponse,
  IAMAccessBindingListResponse,
  IAMAccessBindingResponse,
  IAMRoleListResponse,
  IAMRoleResponse,
  InstallationResponse,
  InstallationDeploymentInventoryResponse,
  NamespaceListResponse,
  NamespaceResponse,
  BackendListResponse,
  RepositoryOptionListResponse,
  SecretListResponse,
  ServiceAccountListResponse,
  ServiceAccountResponse,
  WorkspaceFileResponse,
  WorkspaceFileUpdateResponse,
} from "./resources.ts";

const ErrorResponseRef = Type.Ref("ErrorResponse");
const SecretResponseRef = Type.Ref("SecretResponse");

const readErrors = {
  400: ErrorResponseRef,
  401: ErrorResponseRef,
  403: ErrorResponseRef,
  404: ErrorResponseRef,
  500: ErrorResponseRef,
  503: ErrorResponseRef,
} as const;

const createErrors = {
  ...readErrors,
  409: ErrorResponseRef,
  413: ErrorResponseRef,
  415: ErrorResponseRef,
} as const;

const mutationErrors = {
  ...readErrors,
  409: ErrorResponseRef,
} as const;

export const occApiRoutes = [
  {
    operationId: "createPreset",
    method: "POST",
    path: "/namespaces/:namespaceId/presets",
    action: "openclaw.presets.create",
    iamAction: "create",
    resourceKind: "preset",
    authorizationTarget: "namespace_collection",
    summary: "Create a reusable Namespace-owned Agent Preset",
    tags: ["Presets"],
    schema: {
      querystring: EmptyQuery,
      params: NamespaceParams,
      body: CreatePresetBody,
      response: { 201: PresetResponse, ...createErrors },
    },
  },
  {
    operationId: "listPresets",
    method: "GET",
    path: "/namespaces/:namespaceId/presets",
    action: "openclaw.presets.list",
    iamAction: "read",
    resourceKind: "preset",
    authorizationTarget: "preset_candidates",
    summary: "List readable Presets in one Namespace",
    tags: ["Presets"],
    schema: {
      querystring: EmptyQuery,
      params: NamespaceParams,
      response: { 200: PresetListResponse, ...readErrors },
    },
  },
  {
    operationId: "getPreset",
    method: "GET",
    path: "/namespaces/:namespaceId/presets/:presetId",
    action: "openclaw.presets.read",
    iamAction: "read",
    resourceKind: "preset",
    authorizationTarget: "preset",
    summary: "Read one exact Namespace-owned Preset",
    tags: ["Presets"],
    schema: {
      querystring: EmptyQuery,
      params: PresetParams,
      response: { 200: PresetResponse, ...readErrors },
    },
  },
  {
    operationId: "updatePreset",
    method: "PATCH",
    path: "/namespaces/:namespaceId/presets/:presetId",
    action: "openclaw.presets.update",
    iamAction: "update",
    resourceKind: "preset",
    authorizationTarget: "preset",
    summary: "Update a Preset without changing existing Agents",
    tags: ["Presets"],
    schema: {
      querystring: EmptyQuery,
      params: PresetParams,
      body: UpdatePresetBody,
      response: { 200: PresetResponse, ...createErrors },
    },
  },
  {
    operationId: "deletePreset",
    method: "DELETE",
    path: "/namespaces/:namespaceId/presets/:presetId",
    action: "openclaw.presets.delete",
    iamAction: "delete",
    resourceKind: "preset",
    authorizationTarget: "preset",
    summary: "Delete a Preset without changing existing Agents",
    tags: ["Presets"],
    schema: {
      querystring: EmptyQuery,
      params: PresetParams,
      response: { 204: Type.Null(), ...mutationErrors },
    },
  },

  {
    operationId: "bootstrapInstallation",
    method: "POST",
    path: "/installation/bootstrap",
    action: "openclaw.installation.bootstrap",
    iamAction: "administer",
    resourceKind: "installation",
    authorizationTarget: "installation",
    summary: "Bootstrap the singleton Installation",
    tags: ["Installation"],
    schema: {
      querystring: EmptyQuery,
      body: NamedResourceBody,
      response: {
        201: InstallationResponse,
        400: ErrorResponseRef,
        401: ErrorResponseRef,
        403: ErrorResponseRef,
        409: ErrorResponseRef,
        413: ErrorResponseRef,
        415: ErrorResponseRef,
        500: ErrorResponseRef,
        503: ErrorResponseRef,
      },
    },
  },
  {
    operationId: "getInstallation",
    method: "GET",
    path: "/installation",
    action: "openclaw.installation.read",
    iamAction: "read",
    resourceKind: "installation",
    authorizationTarget: "installation",
    summary: "Get the singleton Installation",
    tags: ["Installation"],
    schema: {
      querystring: EmptyQuery,
      response: { 200: InstallationResponse, ...readErrors },
    },
  },
  {
    operationId: "getInstallationDeploymentInventory",
    method: "GET",
    path: "/installation/deployment-inventory",
    action: "openclaw.installation.deployment_inventory.read",
    iamAction: "administer",
    resourceKind: "installation",
    authorizationTarget: "installation",
    summary: "Get the complete authorized Agent deployment inventory",
    tags: ["Installation"],
    schema: {
      querystring: EmptyQuery,
      response: { 200: InstallationDeploymentInventoryResponse, ...readErrors },
    },
  },
  {
    operationId: "listBackends",
    method: "GET",
    path: "/backends",
    action: "openclaw.backends.list",
    iamAction: "administer",
    resourceKind: "installation",
    authorizationTarget: "installation",
    summary: "List configured Backends (experimental)",
    tags: ["Backends"],
    schema: {
      querystring: EmptyQuery,
      response: { 200: BackendListResponse, ...readErrors },
    },
  },
  {
    operationId: "createNamespace",
    method: "POST",
    path: "/namespaces",
    action: "openclaw.namespaces.create",
    iamAction: "create",
    resourceKind: "namespace",
    authorizationTarget: "installation_collection",
    summary: "Create an Installation-owned Namespace",
    tags: ["Namespaces"],
    schema: {
      querystring: EmptyQuery,
      body: CreateNamespaceBody,
      response: { 201: NamespaceResponse, ...createErrors },
    },
  },
  {
    operationId: "listNamespaces",
    method: "GET",
    path: "/namespaces",
    action: "openclaw.namespaces.list",
    iamAction: "read",
    resourceKind: "namespace",
    authorizationTarget: "namespace_candidates",
    summary: "List authorized Namespaces",
    tags: ["Namespaces"],
    schema: {
      querystring: EmptyQuery,
      response: { 200: NamespaceListResponse, ...readErrors },
    },
  },
  {
    operationId: "getNamespace",
    method: "GET",
    path: "/namespaces/:namespaceId",
    action: "openclaw.namespaces.read",
    iamAction: "read",
    resourceKind: "namespace",
    authorizationTarget: "namespace",
    summary: "Get an exact Installation-owned Namespace",
    tags: ["Namespaces"],
    schema: {
      querystring: EmptyQuery,
      params: NamespaceParams,
      response: { 200: NamespaceResponse, ...readErrors },
    },
  },
  {
    operationId: "deleteNamespace",
    method: "DELETE",
    path: "/namespaces/:namespaceId",
    action: "openclaw.namespaces.delete",
    iamAction: "delete",
    resourceKind: "namespace",
    authorizationTarget: "namespace",
    summary: "Begin deletion of an empty Installation-owned Namespace",
    tags: ["Namespaces"],
    schema: {
      querystring: EmptyQuery,
      params: NamespaceParams,
      response: { 202: NamespaceResponse, ...mutationErrors },
    },
  },
  {
    operationId: "listIAMRoles",
    method: "GET",
    path: "/namespaces/:namespaceId/iam/roles",
    action: "openclaw.iam.roles.list",
    iamAction: "administer",
    resourceKind: "installation",
    authorizationTarget: "namespace_iam",
    summary: "List exact Namespace IAM Roles",
    tags: ["IAM"],
    schema: {
      querystring: EmptyQuery,
      params: NamespaceParams,
      response: { 200: IAMRoleListResponse, ...readErrors },
    },
  },
  {
    operationId: "createIAMRole",
    method: "POST",
    path: "/namespaces/:namespaceId/iam/roles",
    action: "openclaw.iam.roles.create",
    iamAction: "administer",
    resourceKind: "installation",
    authorizationTarget: "namespace_iam",
    summary: "Create an immutable Namespace IAM Role",
    tags: ["IAM"],
    schema: {
      querystring: EmptyQuery,
      params: NamespaceParams,
      body: CreateIAMRoleBody,
      response: { 201: IAMRoleResponse, ...createErrors },
    },
  },
  {
    operationId: "getIAMRole",
    method: "GET",
    path: "/namespaces/:namespaceId/iam/roles/:roleId",
    action: "openclaw.iam.roles.read",
    iamAction: "administer",
    resourceKind: "installation",
    authorizationTarget: "namespace_iam",
    summary: "Get an exact Namespace IAM Role",
    tags: ["IAM"],
    schema: {
      querystring: EmptyQuery,
      params: IAMRoleParams,
      response: { 200: IAMRoleResponse, ...readErrors },
    },
  },
  {
    operationId: "deleteIAMRole",
    method: "DELETE",
    path: "/namespaces/:namespaceId/iam/roles/:roleId",
    action: "openclaw.iam.roles.delete",
    iamAction: "administer",
    resourceKind: "installation",
    authorizationTarget: "namespace_iam",
    summary: "Delete an unreferenced exact Namespace IAM Role",
    tags: ["IAM"],
    schema: {
      querystring: EmptyQuery,
      params: IAMRoleParams,
      response: { 204: Type.Null(), ...mutationErrors },
    },
  },
  {
    operationId: "listIAMAccessBindings",
    method: "GET",
    path: "/namespaces/:namespaceId/iam/access-bindings",
    action: "openclaw.iam.access_bindings.list",
    iamAction: "administer",
    resourceKind: "installation",
    authorizationTarget: "namespace_iam",
    summary: "List exact Namespace IAM AccessBindings",
    tags: ["IAM"],
    schema: {
      querystring: EmptyQuery,
      params: NamespaceParams,
      response: { 200: IAMAccessBindingListResponse, ...readErrors },
    },
  },
  {
    operationId: "createIAMAccessBinding",
    method: "POST",
    path: "/namespaces/:namespaceId/iam/access-bindings",
    action: "openclaw.iam.access_bindings.create",
    iamAction: "administer",
    resourceKind: "installation",
    authorizationTarget: "namespace_iam",
    summary: "Create an immutable exact-resource Namespace IAM AccessBinding",
    tags: ["IAM"],
    schema: {
      querystring: EmptyQuery,
      params: NamespaceParams,
      body: CreateIAMAccessBindingBody,
      response: { 201: IAMAccessBindingResponse, ...createErrors },
    },
  },
  {
    operationId: "getIAMAccessBinding",
    method: "GET",
    path: "/namespaces/:namespaceId/iam/access-bindings/:bindingId",
    action: "openclaw.iam.access_bindings.read",
    iamAction: "administer",
    resourceKind: "installation",
    authorizationTarget: "namespace_iam",
    summary: "Get an exact Namespace IAM AccessBinding",
    tags: ["IAM"],
    schema: {
      querystring: EmptyQuery,
      params: IAMAccessBindingParams,
      response: { 200: IAMAccessBindingResponse, ...readErrors },
    },
  },
  {
    operationId: "deleteIAMAccessBinding",
    method: "DELETE",
    path: "/namespaces/:namespaceId/iam/access-bindings/:bindingId",
    action: "openclaw.iam.access_bindings.delete",
    iamAction: "administer",
    resourceKind: "installation",
    authorizationTarget: "namespace_iam",
    summary: "Delete one exact Namespace IAM AccessBinding",
    tags: ["IAM"],
    schema: {
      querystring: EmptyQuery,
      params: IAMAccessBindingParams,
      response: { 204: Type.Null(), ...mutationErrors },
    },
  },
  {
    operationId: "createConfiguration",
    method: "POST",
    path: "/namespaces/:namespaceId/configurations",
    action: "openclaw.configurations.create",
    iamAction: "create",
    resourceKind: "configuration",
    authorizationTarget: "namespace_collection",
    summary: "Create a native Namespace-owned Agent Configuration",
    tags: ["Configurations"],
    schema: {
      querystring: EmptyQuery,
      params: NamespaceParams,
      body: CreateConfigurationBody,
      response: { 201: ConfigurationResponse, ...createErrors },
    },
  },
  {
    operationId: "getConfiguration",
    method: "GET",
    path: "/namespaces/:namespaceId/configurations/:configurationId",
    action: "openclaw.configurations.read",
    iamAction: "read",
    resourceKind: "configuration",
    authorizationTarget: "configuration",
    summary: "Get an exact Namespace-owned Configuration",
    tags: ["Configurations"],
    schema: {
      querystring: EmptyQuery,
      params: ConfigurationParams,
      response: { 200: ConfigurationResponse, ...readErrors },
    },
  },
  {
    operationId: "updateConfiguration",
    method: "PATCH",
    path: "/namespaces/:namespaceId/configurations/:configurationId",
    action: "openclaw.configurations.update",
    iamAction: "update",
    resourceKind: "configuration",
    authorizationTarget: "configuration",
    summary: "Replace values and increment an exact Namespace-owned Configuration generation",
    tags: ["Configurations"],
    schema: {
      querystring: EmptyQuery,
      params: ConfigurationParams,
      body: UpdateConfigurationBody,
      response: { 200: ConfigurationResponse, ...createErrors },
    },
  },
  {
    operationId: "deleteConfiguration",
    method: "DELETE",
    path: "/namespaces/:namespaceId/configurations/:configurationId",
    action: "openclaw.configurations.delete",
    iamAction: "delete",
    resourceKind: "configuration",
    authorizationTarget: "configuration",
    summary: "Delete an exact unreferenced Namespace-owned Configuration",
    tags: ["Configurations"],
    schema: {
      querystring: EmptyQuery,
      params: ConfigurationParams,
      response: { 204: Type.Null(), ...mutationErrors },
    },
  },
  {
    operationId: "createSecret",
    method: "POST",
    path: "/namespaces/:namespaceId/secrets",
    action: "openclaw.secrets.create",
    iamAction: "create",
    resourceKind: "secret",
    authorizationTarget: "namespace_collection",
    summary: "Create exact Namespace-owned Secret material and return metadata only",
    tags: ["Secrets"],
    schema: {
      querystring: EmptyQuery,
      params: NamespaceParams,
      body: CreateSecretBody,
      response: { 201: SecretResponseRef, ...createErrors },
    },
  },
  {
    operationId: "listSecrets",
    method: "GET",
    path: "/namespaces/:namespaceId/secrets",
    action: "openclaw.secrets.read",
    iamAction: "read",
    resourceKind: "secret",
    authorizationTarget: "namespace_collection",
    summary: "List readable Namespace-owned Secret metadata without revealing material",
    tags: ["Secrets"],
    schema: {
      querystring: EmptyQuery,
      params: NamespaceParams,
      response: { 200: SecretListResponse, ...readErrors },
    },
  },
  {
    operationId: "getSecret",
    method: "GET",
    path: "/namespaces/:namespaceId/secrets/:secretId",
    action: "openclaw.secrets.read",
    iamAction: "read",
    resourceKind: "secret",
    authorizationTarget: "secret",
    summary: "Get exact Namespace-owned Secret metadata without revealing material",
    tags: ["Secrets"],
    schema: {
      querystring: EmptyQuery,
      params: SecretParams,
      response: { 200: SecretResponseRef, ...readErrors },
    },
  },
  {
    operationId: "updateSecret",
    method: "PATCH",
    path: "/namespaces/:namespaceId/secrets/:secretId",
    action: "openclaw.secrets.update",
    iamAction: "update",
    resourceKind: "secret",
    authorizationTarget: "secret",
    summary: "Replace exact Namespace-owned Secret material and return stable metadata",
    tags: ["Secrets"],
    schema: {
      querystring: EmptyQuery,
      params: SecretParams,
      body: UpdateSecretBody,
      response: { 200: SecretResponseRef, ...createErrors },
    },
  },
  {
    operationId: "deleteSecret",
    method: "DELETE",
    path: "/namespaces/:namespaceId/secrets/:secretId",
    action: "openclaw.secrets.delete",
    iamAction: "delete",
    resourceKind: "secret",
    authorizationTarget: "secret",
    summary: "Delete exact unbound Namespace-owned Secret material",
    tags: ["Secrets"],
    schema: {
      querystring: EmptyQuery,
      params: SecretParams,
      response: { 204: Type.Null(), ...mutationErrors },
    },
  },
  {
    operationId: "createServiceAccount",
    method: "POST",
    path: "/namespaces/:namespaceId/service-accounts",
    action: "openclaw.service_accounts.create",
    iamAction: "create",
    resourceKind: "service_account",
    authorizationTarget: "namespace_collection",
    summary: "Create a native Namespace-owned ServiceAccount",
    tags: ["Service accounts"],
    schema: {
      querystring: EmptyQuery,
      params: NamespaceParams,
      body: CreateServiceAccountBody,
      response: { 201: ServiceAccountResponse, ...createErrors },
    },
  },
  {
    operationId: "listServiceAccounts",
    method: "GET",
    path: "/namespaces/:namespaceId/service-accounts",
    action: "openclaw.service_accounts.list",
    iamAction: "read",
    resourceKind: "service_account",
    authorizationTarget: "namespace_and_service_account_candidates",
    summary: "List authorized Namespace-owned ServiceAccounts in one exact Namespace",
    tags: ["Service accounts"],
    schema: {
      querystring: EmptyQuery,
      params: NamespaceParams,
      response: { 200: ServiceAccountListResponse, ...readErrors },
    },
  },
  {
    operationId: "getServiceAccount",
    method: "GET",
    path: "/namespaces/:namespaceId/service-accounts/:serviceAccountId",
    action: "openclaw.service_accounts.read",
    iamAction: "read",
    resourceKind: "service_account",
    authorizationTarget: "service_account",
    summary: "Get an exact Namespace-owned ServiceAccount",
    tags: ["Service accounts"],
    schema: {
      querystring: EmptyQuery,
      params: ServiceAccountParams,
      response: { 200: ServiceAccountResponse, ...readErrors },
    },
  },
  {
    operationId: "createServiceAccountCredential",
    method: "POST",
    path: "/namespaces/:namespaceId/service-accounts/:serviceAccountId/credentials",
    action: "openclaw.service_accounts.credentials.create",
    iamAction: "update",
    resourceKind: "service_account",
    authorizationTarget: "service_account",
    summary: "Issue a managed credential for an exact Namespace-owned ServiceAccount",
    tags: ["Service accounts"],
    schema: {
      querystring: EmptyQuery,
      params: ServiceAccountParams,
      body: CreateServiceAccountCredentialBody,
      response: { 201: ServiceAccountResponse, ...createErrors },
    },
  },
  {
    operationId: "updateServiceAccountCredential",
    method: "PATCH",
    path: "/namespaces/:namespaceId/service-accounts/:serviceAccountId/credential",
    action: "openclaw.service_accounts.update",
    iamAction: "update",
    resourceKind: "service_account",
    authorizationTarget: "service_account",
    summary: "Associate an exact Namespace-local credential reference with a ServiceAccount",
    tags: ["Service accounts"],
    schema: {
      querystring: EmptyQuery,
      params: ServiceAccountParams,
      body: UpdateServiceAccountCredentialBody,
      response: { 200: ServiceAccountResponse, ...createErrors },
    },
  },
  {
    operationId: "deleteServiceAccount",
    method: "DELETE",
    path: "/namespaces/:namespaceId/service-accounts/:serviceAccountId",
    action: "openclaw.service_accounts.delete",
    iamAction: "delete",
    resourceKind: "service_account",
    authorizationTarget: "service_account",
    summary: "Delete an exact unreferenced Namespace-owned ServiceAccount",
    tags: ["Service accounts"],
    schema: {
      querystring: EmptyQuery,
      params: ServiceAccountParams,
      response: { 204: Type.Null(), ...mutationErrors },
    },
  },
  {
    operationId: "discoverAgentModels",
    method: "POST",
    path: "/namespaces/:namespaceId/agents/models",
    action: "openclaw.agents.models.discover",
    iamAction: "create",
    resourceKind: "agent",
    authorizationTarget: "namespace_collection",
    summary: "List provider models for Agent creation without storing the supplied credential",
    tags: ["Agents"],
    schema: {
      querystring: EmptyQuery,
      params: NamespaceParams,
      body: DiscoverAgentModelsBody,
      response: {
        200: AgentModelListResponse,
        429: ErrorResponseRef,
        501: ErrorResponseRef,
        ...createErrors,
      },
    },
  },
  {
    operationId: "discoverAgentPlugins",
    method: "POST",
    path: "/namespaces/:namespaceId/agents/plugins",
    action: "openclaw.agents.plugins.discover",
    iamAction: "create",
    resourceKind: "agent",
    authorizationTarget: "namespace_collection",
    summary: "List available plugins for Agent creation using the selected Driver",
    tags: ["Agents"],
    schema: {
      querystring: EmptyQuery,
      params: NamespaceParams,
      body: DiscoverAgentPluginsBody,
      response: {
        200: AgentPluginCatalogResponse,
        429: ErrorResponseRef,
        501: ErrorResponseRef,
        ...createErrors,
      },
    },
  },
  {
    operationId: "discoverAgentPluginDetails",
    method: "POST",
    path: "/namespaces/:namespaceId/agents/plugins/details",
    action: "openclaw.agents.plugins.details",
    iamAction: "create",
    resourceKind: "agent",
    authorizationTarget: "namespace_collection",
    summary: "Read plugin details using the selected Driver",
    tags: ["Agents"],
    schema: {
      querystring: EmptyQuery,
      params: NamespaceParams,
      body: DiscoverAgentPluginDetailsBody,
      response: {
        200: AgentPluginDetailsResponse,
        429: ErrorResponseRef,
        501: ErrorResponseRef,
        ...createErrors,
      },
    },
  },
  {
    operationId: "getSavedAgentPluginPolicyCapabilities",
    method: "GET",
    path: "/namespaces/:namespaceId/agents/:agentId/plugins/capabilities",
    action: "openclaw.agents.plugins.saved.capabilities.read",
    iamAction: "update",
    resourceKind: "agent",
    authorizationTarget: "agent",
    summary:
      "Read selected Plugin Driver policy capabilities for an active Agent with caller Agent read/update permission",
    tags: ["Agents"],
    schema: {
      querystring: EmptyQuery,
      params: AgentParams,
      response: {
        200: AgentPluginPolicyCapabilitiesResponse,
        501: ErrorResponseRef,
        ...createErrors,
      },
    },
  },
  {
    operationId: "discoverSavedAgentPlugins",
    method: "POST",
    path: "/namespaces/:namespaceId/agents/:agentId/plugins",
    action: "openclaw.agents.plugins.saved.discover",
    iamAction: "update",
    resourceKind: "agent",
    authorizationTarget: "agent",
    summary:
      "List plugins for an active Agent; caller needs Agent read/update. Curated discovery needs no Secret; hosted discovery needs the Agent's bound Service Accounts Secret with caller and Agent Secret operate grants",
    tags: ["Agents"],
    schema: {
      querystring: EmptyQuery,
      params: AgentParams,
      body: DiscoverSavedAgentPluginsBody,
      response: {
        200: AgentPluginCatalogResponse,
        429: ErrorResponseRef,
        501: ErrorResponseRef,
        ...createErrors,
      },
    },
  },
  {
    operationId: "discoverSavedAgentPluginDetails",
    method: "POST",
    path: "/namespaces/:namespaceId/agents/:agentId/plugins/details",
    action: "openclaw.agents.plugins.saved.details",
    iamAction: "update",
    resourceKind: "agent",
    authorizationTarget: "agent",
    summary:
      "Read plugin details for an active Agent; caller needs Agent read/update. Curated discovery needs no Secret; hosted discovery needs the Agent's bound Service Accounts Secret with caller and Agent Secret operate grants",
    tags: ["Agents"],
    schema: {
      querystring: EmptyQuery,
      params: AgentParams,
      body: DiscoverSavedAgentPluginDetailsBody,
      response: {
        200: AgentPluginDetailsResponse,
        429: ErrorResponseRef,
        501: ErrorResponseRef,
        ...createErrors,
      },
    },
  },
  {
    operationId: "provisionAgent",
    method: "POST",
    path: "/namespaces/:namespaceId/agents/provision",
    action: "openclaw.agents.provision",
    iamAction: "create",
    resourceKind: "agent",
    authorizationTarget: "namespace_collection",
    summary: "Create a new Agent and queue first-time provisioning",
    tags: ["Agents"],
    schema: {
      querystring: EmptyQuery,
      params: NamespaceParams,
      body: ProvisionAgentBody,
      response: { 202: AgentProvisioningResponse, ...createErrors },
    },
  },
  {
    operationId: "listRepositoryOptions",
    method: "GET",
    path: "/namespaces/:namespaceId/agents/repository-options",
    action: "openclaw.agents.repository_options.list",
    iamAction: "create",
    resourceKind: "agent",
    authorizationTarget: "namespace_collection",
    summary: "List approved repository choices for Agent creation in one Namespace",
    tags: ["Agents"],
    schema: {
      querystring: EmptyQuery,
      params: NamespaceParams,
      response: {
        200: RepositoryOptionListResponse,
        ...readErrors,
        409: ErrorResponseRef,
        503: Type.Ref("ErrorResponse", {
          description:
            "Check `error.code`: `REPOSITORY_OPTIONS_UNAVAILABLE` means optional repository discovery is unavailable after Namespace lifecycle and Agent create authorization checks. Creation without repository bindings remains available subject to fresh authorization. `DEPENDENCY_UNAVAILABLE` includes IAM and other required dependency failures and does not permit proceeding. Successful discovery returns a data array, including an empty array when no repositories are approved.",
        }),
      },
    },
  },
  {
    operationId: "createAgent",
    method: "POST",
    path: "/namespaces/:namespaceId/agents",
    action: "openclaw.agents.create",
    iamAction: "create",
    resourceKind: "agent",
    authorizationTarget: "namespace_collection",
    summary: "Create a Namespace-owned Agent",
    tags: ["Agents"],
    schema: {
      querystring: EmptyQuery,
      params: NamespaceParams,
      body: CreateAgentBody,
      response: { 201: AgentResponse, ...createErrors },
    },
  },
  {
    operationId: "updateAgent",
    method: "PATCH",
    path: "/namespaces/:namespaceId/agents/:agentId",
    action: "openclaw.agents.update",
    iamAction: "update",
    resourceKind: "agent",
    authorizationTarget: "agent",
    summary: "Replace an exact Namespace-owned Agent's editable draft",
    tags: ["Agents"],
    schema: {
      querystring: EmptyQuery,
      params: AgentParams,
      body: UpdateAgentBody,
      response: { 200: AgentResponse, ...createErrors },
    },
  },
  {
    operationId: "listAgents",
    method: "GET",
    path: "/namespaces/:namespaceId/agents",
    action: "openclaw.agents.list",
    iamAction: "read",
    resourceKind: "agent",
    authorizationTarget: "namespace_and_agent_candidates",
    summary: "List authorized Agents in one exact Namespace",
    tags: ["Agents"],
    schema: {
      querystring: EmptyQuery,
      params: NamespaceParams,
      response: { 200: AgentListResponse, ...readErrors },
    },
  },
  {
    operationId: "getAgent",
    method: "GET",
    path: "/namespaces/:namespaceId/agents/:agentId",
    action: "openclaw.agents.read",
    iamAction: "read",
    resourceKind: "agent",
    authorizationTarget: "agent",
    summary: "Get an exact Namespace-owned Agent",
    tags: ["Agents"],
    schema: {
      querystring: EmptyQuery,
      params: AgentParams,
      response: { 200: AgentResponse, ...readErrors },
    },
  },
  {
    operationId: "getAgentProvisioning",
    method: "GET",
    path: "/namespaces/:namespaceId/agents/provision/:workId",
    action: "openclaw.agents.provisioning.read",
    iamAction: "read",
    resourceKind: "agent",
    authorizationTarget: "agent",
    summary: "Get first-time provisioning status for one exact work item",
    tags: ["Agents"],
    schema: {
      querystring: EmptyQuery,
      params: AgentProvisioningParams,
      response: { 200: AgentProvisioningStatusResponse, ...readErrors },
    },
  },
  {
    operationId: "retryAgentProvisioning",
    method: "POST",
    path: "/namespaces/:namespaceId/agents/provision/:workId/retry",
    action: "openclaw.agents.provisioning.retry",
    iamAction: "operate",
    resourceKind: "agent",
    authorizationTarget: "agent",
    summary: "Retry failed first-time provisioning for one exact work item",
    tags: ["Agents"],
    schema: {
      querystring: EmptyQuery,
      params: AgentProvisioningParams,
      response: { 202: AgentProvisioningStatusResponse, ...mutationErrors },
    },
  },
  {
    operationId: "deleteAgent",
    method: "DELETE",
    path: "/namespaces/:namespaceId/agents/:agentId",
    action: "openclaw.agents.delete",
    iamAction: "delete",
    resourceKind: "agent",
    authorizationTarget: "agent",
    summary: "Begin deletion of an exact Namespace-owned Agent and its AgentRevisions",
    tags: ["Agents"],
    schema: {
      querystring: EmptyQuery,
      params: AgentParams,
      response: { 202: AgentResponse, ...mutationErrors },
    },
  },
  {
    operationId: "getAgentRuntimeCredentials",
    method: "GET",
    path: "/namespaces/:namespaceId/agents/:agentId/runtime-credentials",
    action: "openclaw.agents.runtime_credentials.read",
    iamAction: "read",
    resourceKind: "agent",
    authorizationTarget: "agent",
    summary: "Get metadata for one Agent's provisioned runtime credentials",
    tags: ["Agents"],
    schema: {
      querystring: EmptyQuery,
      params: AgentParams,
      response: { 200: AgentRuntimeCredentialResponse, ...readErrors },
    },
  },
  {
    operationId: "getAgentRuntimeImages",
    method: "GET",
    path: "/namespaces/:namespaceId/agents/:agentId/runtime-images",
    action: "openclaw.agents.runtime_images.read",
    iamAction: "read",
    resourceKind: "agent",
    authorizationTarget: "agent",
    summary: "Read observed images and source commits for an Agent's active runtime",
    tags: ["Agents"],
    schema: {
      querystring: EmptyQuery,
      params: AgentParams,
      response: { 200: AgentRuntimeImagesResponse, ...readErrors },
    },
  },
  {
    operationId: "provisionAgentRuntimeCredentials",
    method: "POST",
    path: "/namespaces/:namespaceId/agents/:agentId/runtime-credentials",
    action: "openclaw.agents.runtime_credentials.provision",
    iamAction: "operate",
    resourceKind: "agent",
    authorizationTarget: "agent",
    summary: "Provision initial runtime credentials for one undeployed Agent",
    tags: ["Agents"],
    schema: {
      querystring: EmptyQuery,
      params: AgentParams,
      body: AgentRuntimeCredentialsBody,
      response: { 200: AgentRuntimeCredentialResponse, ...createErrors },
    },
  },
  {
    operationId: "deployAgent",
    method: "POST",
    path: "/namespaces/:namespaceId/agents/:agentId/deploy",
    action: "openclaw.agents.deploy",
    iamAction: "deploy",
    resourceKind: "agent",
    authorizationTarget: "agent",
    summary: "Admit an immutable revision from the Agent's saved draft",
    tags: ["Agents"],
    schema: {
      querystring: EmptyQuery,
      params: AgentParams,
      response: { 202: AgentRevisionResponse, ...mutationErrors },
    },
  },
  {
    operationId: "stopAgent",
    method: "POST",
    path: "/namespaces/:namespaceId/agents/:agentId/stop",
    action: "openclaw.agents.stop",
    iamAction: "operate",
    resourceKind: "agent",
    authorizationTarget: "agent",
    summary: "Stop one Agent while retaining its revision and persistent state",
    tags: ["Agents"],
    schema: {
      querystring: EmptyQuery,
      params: AgentParams,
      response: { 202: AgentResponse, ...mutationErrors },
    },
  },
  {
    operationId: "getAgentWorkspaceFile",
    method: "GET",
    path: "/namespaces/:namespaceId/agents/:agentId/workspace/files/:name",
    action: "openclaw.agents.workspace.files.read",
    iamAction: "read",
    resourceKind: "agent",
    authorizationTarget: "agent",
    summary: "Read an allowed workspace file from one active Agent",
    tags: ["Agents"],
    schema: {
      querystring: EmptyQuery,
      params: WorkspaceFileParams,
      response: { 200: WorkspaceFileResponse, ...readErrors },
    },
  },
  {
    operationId: "putAgentWorkspaceFile",
    method: "PUT",
    path: "/namespaces/:namespaceId/agents/:agentId/workspace/files/:name",
    action: "openclaw.agents.workspace.files.write",
    iamAction: "operate",
    resourceKind: "agent",
    authorizationTarget: "agent",
    summary: "Create or replace an allowed workspace file for one active Agent",
    tags: ["Agents"],
    schema: {
      querystring: EmptyQuery,
      params: WorkspaceFileParams,
      body: UpdateWorkspaceFileBody,
      response: {
        200: WorkspaceFileUpdateResponse,
        ...createErrors,
        503: Type.Ref("ErrorResponse", {
          description:
            "Service Unavailable. Check `error.code`: `DEPENDENCY_UNAVAILABLE` means workspace access is unavailable. `UNKNOWN_OUTCOME` means OCC could not confirm the write or its audit record; the file may already contain the requested content. Read the same file with `GET` and compare its content before deciding whether to retry. If the content matches, do not retry. If you cannot read it, wait or ask someone with `read` permission on the Agent to check.",
        }),
      },
    },
  },
  {
    operationId: "listAgentRevisions",
    method: "GET",
    path: "/namespaces/:namespaceId/agents/:agentId/revisions",
    action: "openclaw.agent_revisions.list",
    iamAction: "read",
    resourceKind: "agent",
    authorizationTarget: "agent_collection",
    summary: "List authorized immutable revisions for one exact Agent",
    tags: ["Agent revisions"],
    schema: {
      querystring: EmptyQuery,
      params: AgentParams,
      response: { 200: AgentRevisionListResponse, ...readErrors },
    },
  },
  {
    operationId: "getAgentRevision",
    method: "GET",
    path: "/namespaces/:namespaceId/agents/:agentId/revisions/:revisionId",
    action: "openclaw.agent_revisions.read",
    iamAction: "read",
    resourceKind: "agent_revision",
    authorizationTarget: "requested_revision",
    summary: "Get an exact authorized immutable Agent revision",
    tags: ["Agent revisions"],
    schema: {
      querystring: EmptyQuery,
      params: RevisionParams,
      response: { 200: AgentRevisionResponse, ...readErrors },
    },
  },
  {
    operationId: "getAgentDeployment",
    method: "GET",
    path: "/namespaces/:namespaceId/agents/:agentId/deployments/:deploymentId",
    action: "openclaw.agent_deployments.read",
    iamAction: "read",
    resourceKind: "agent_revision",
    authorizationTarget: "requested_revision",
    summary: "Get the durable deployment status for one admitted Agent revision",
    tags: ["Agent deployments"],
    schema: {
      querystring: EmptyQuery,
      params: DeploymentParams,
      response: { 200: AgentDeploymentStatusResponse, ...readErrors },
    },
  },
  {
    operationId: "diagnoseAgentDeployment",
    method: "POST",
    path: "/namespaces/:namespaceId/agents/:agentId/deployments/:deploymentId/diagnostics",
    action: "openclaw.agent_deployments.diagnostics.run",
    iamAction: "operate",
    resourceKind: "agent",
    authorizationTarget: "agent_deployment_diagnostics",
    summary: "Run explicit current-runtime diagnostics for one exact Agent revision",
    tags: ["Agent deployments"],
    schema: {
      querystring: EmptyQuery,
      params: DeploymentParams,
      response: { 200: AgentDeploymentDiagnosticsResponse, ...mutationErrors },
    },
  },
] as const;

export type OccApiRoute = (typeof occApiRoutes)[number];
export type OccApiOperationId = OccApiRoute["operationId"];
