import { Type } from "typebox";

import {
  AgentParams,
  AgentRuntimeCredentialsBody,
  ConfigurationParams,
  CreateAgentBody,
  CreateConfigurationBody,
  CreateNamespaceBody,
  CreateSecretBody,
  CreateServiceAccountBody,
  CreateServiceAccountCredentialBody,
  EmptyQuery,
  NamedResourceBody,
  NamespaceParams,
  RevisionParams,
  SecretParams,
  ServiceAccountParams,
  UpdateAgentBody,
  UpdateConfigurationBody,
  UpdateSecretBody,
  UpdateServiceAccountCredentialBody,
  UpdateWorkspaceFileBody,
  WorkspaceFileParams,
} from "./common.ts";
import {
  AgentListResponse,
  AgentRuntimeCredentialResponse,
  AgentResponse,
  AgentRevisionListResponse,
  AgentRevisionResponse,
  ConfigurationResponse,
  InstallationResponse,
  NamespaceListResponse,
  NamespaceResponse,
  ProviderListResponse,
  ServiceAccountListResponse,
  ServiceAccountResponse,
  WorkspaceFileResponse,
  WorkspaceFileUpdateResponse,
} from "./resources.ts";

const ErrorResponseRef = Type.Ref("ErrorResponse");
const SecretResponseRef = Type.Ref("SecretResponse");

const readErrors = {
  400: ErrorResponseRef,
  401: ErrorResponseRef,
  403: ErrorResponseRef,
  404: ErrorResponseRef,
  500: ErrorResponseRef,
  503: ErrorResponseRef,
} as const;

const createErrors = {
  ...readErrors,
  409: ErrorResponseRef,
  413: ErrorResponseRef,
  415: ErrorResponseRef,
} as const;

const mutationErrors = {
  ...readErrors,
  409: ErrorResponseRef,
} as const;

export const occApiRoutes = [
  {
    operationId: "bootstrapInstallation",
    method: "POST",
    path: "/installation/bootstrap",
    action: "openclaw.installation.bootstrap",
    iamAction: "administer",
    resourceKind: "installation",
    authorizationTarget: "installation",
    summary: "Bootstrap the singleton Installation",
    tags: ["Installation"],
    schema: {
      querystring: EmptyQuery,
      body: NamedResourceBody,
      response: {
        201: InstallationResponse,
        400: ErrorResponseRef,
        401: ErrorResponseRef,
        403: ErrorResponseRef,
        409: ErrorResponseRef,
        413: ErrorResponseRef,
        415: ErrorResponseRef,
        500: ErrorResponseRef,
        503: ErrorResponseRef,
      },
    },
  },
  {
    operationId: "getInstallation",
    method: "GET",
    path: "/installation",
    action: "openclaw.installation.read",
    iamAction: "read",
    resourceKind: "installation",
    authorizationTarget: "installation",
    summary: "Get the singleton Installation",
    tags: ["Installation"],
    schema: {
      querystring: EmptyQuery,
      response: { 200: InstallationResponse, ...readErrors },
    },
  },
  {
    operationId: "listProviders",
    method: "GET",
    path: "/providers",
    action: "openclaw.providers.list",
    iamAction: "administer",
    resourceKind: "installation",
    authorizationTarget: "installation",
    summary: "List configured Providers",
    tags: ["Providers"],
    schema: {
      querystring: EmptyQuery,
      response: { 200: ProviderListResponse, ...readErrors },
    },
  },
  {
    operationId: "createNamespace",
    method: "POST",
    path: "/namespaces",
    action: "openclaw.namespaces.create",
    iamAction: "create",
    resourceKind: "namespace",
    authorizationTarget: "installation_collection",
    summary: "Create an Installation-owned Namespace",
    tags: ["Namespaces"],
    schema: {
      querystring: EmptyQuery,
      body: CreateNamespaceBody,
      response: { 201: NamespaceResponse, ...createErrors },
    },
  },
  {
    operationId: "listNamespaces",
    method: "GET",
    path: "/namespaces",
    action: "openclaw.namespaces.list",
    iamAction: "read",
    resourceKind: "namespace",
    authorizationTarget: "namespace_candidates",
    summary: "List authorized Namespaces",
    tags: ["Namespaces"],
    schema: {
      querystring: EmptyQuery,
      response: { 200: NamespaceListResponse, ...readErrors },
    },
  },
  {
    operationId: "getNamespace",
    method: "GET",
    path: "/namespaces/:namespaceId",
    action: "openclaw.namespaces.read",
    iamAction: "read",
    resourceKind: "namespace",
    authorizationTarget: "namespace",
    summary: "Get an exact Installation-owned Namespace",
    tags: ["Namespaces"],
    schema: {
      querystring: EmptyQuery,
      params: NamespaceParams,
      response: { 200: NamespaceResponse, ...readErrors },
    },
  },
  {
    operationId: "deleteNamespace",
    method: "DELETE",
    path: "/namespaces/:namespaceId",
    action: "openclaw.namespaces.delete",
    iamAction: "delete",
    resourceKind: "namespace",
    authorizationTarget: "namespace",
    summary: "Begin deletion of an empty Installation-owned Namespace",
    tags: ["Namespaces"],
    schema: {
      querystring: EmptyQuery,
      params: NamespaceParams,
      response: { 202: NamespaceResponse, ...mutationErrors },
    },
  },
  {
    operationId: "createConfiguration",
    method: "POST",
    path: "/namespaces/:namespaceId/configurations",
    action: "openclaw.configurations.create",
    iamAction: "create",
    resourceKind: "configuration",
    authorizationTarget: "namespace_collection",
    summary: "Create a native Namespace-owned Agent Configuration",
    tags: ["Configurations"],
    schema: {
      querystring: EmptyQuery,
      params: NamespaceParams,
      body: CreateConfigurationBody,
      response: { 201: ConfigurationResponse, ...createErrors },
    },
  },
  {
    operationId: "getConfiguration",
    method: "GET",
    path: "/namespaces/:namespaceId/configurations/:configurationId",
    action: "openclaw.configurations.read",
    iamAction: "read",
    resourceKind: "configuration",
    authorizationTarget: "configuration",
    summary: "Get an exact Namespace-owned Configuration",
    tags: ["Configurations"],
    schema: {
      querystring: EmptyQuery,
      params: ConfigurationParams,
      response: { 200: ConfigurationResponse, ...readErrors },
    },
  },
  {
    operationId: "updateConfiguration",
    method: "PATCH",
    path: "/namespaces/:namespaceId/configurations/:configurationId",
    action: "openclaw.configurations.update",
    iamAction: "update",
    resourceKind: "configuration",
    authorizationTarget: "configuration",
    summary: "Replace values and increment an exact Namespace-owned Configuration generation",
    tags: ["Configurations"],
    schema: {
      querystring: EmptyQuery,
      params: ConfigurationParams,
      body: UpdateConfigurationBody,
      response: { 200: ConfigurationResponse, ...createErrors },
    },
  },
  {
    operationId: "deleteConfiguration",
    method: "DELETE",
    path: "/namespaces/:namespaceId/configurations/:configurationId",
    action: "openclaw.configurations.delete",
    iamAction: "delete",
    resourceKind: "configuration",
    authorizationTarget: "configuration",
    summary: "Delete an exact unreferenced Namespace-owned Configuration",
    tags: ["Configurations"],
    schema: {
      querystring: EmptyQuery,
      params: ConfigurationParams,
      response: { 204: Type.Null(), ...mutationErrors },
    },
  },
  {
    operationId: "createSecret",
    method: "POST",
    path: "/namespaces/:namespaceId/secrets",
    action: "openclaw.secrets.create",
    iamAction: "create",
    resourceKind: "secret",
    authorizationTarget: "namespace_collection",
    summary: "Create exact Namespace-owned Secret material and return metadata only",
    tags: ["Secrets"],
    schema: {
      querystring: EmptyQuery,
      params: NamespaceParams,
      body: CreateSecretBody,
      response: { 201: SecretResponseRef, ...createErrors },
    },
  },
  {
    operationId: "getSecret",
    method: "GET",
    path: "/namespaces/:namespaceId/secrets/:secretId",
    action: "openclaw.secrets.read",
    iamAction: "read",
    resourceKind: "secret",
    authorizationTarget: "secret",
    summary: "Get exact Namespace-owned Secret metadata without revealing material",
    tags: ["Secrets"],
    schema: {
      querystring: EmptyQuery,
      params: SecretParams,
      response: { 200: SecretResponseRef, ...readErrors },
    },
  },
  {
    operationId: "updateSecret",
    method: "PATCH",
    path: "/namespaces/:namespaceId/secrets/:secretId",
    action: "openclaw.secrets.update",
    iamAction: "update",
    resourceKind: "secret",
    authorizationTarget: "secret",
    summary: "Replace exact Namespace-owned Secret material and return stable metadata",
    tags: ["Secrets"],
    schema: {
      querystring: EmptyQuery,
      params: SecretParams,
      body: UpdateSecretBody,
      response: { 200: SecretResponseRef, ...createErrors },
    },
  },
  {
    operationId: "deleteSecret",
    method: "DELETE",
    path: "/namespaces/:namespaceId/secrets/:secretId",
    action: "openclaw.secrets.delete",
    iamAction: "delete",
    resourceKind: "secret",
    authorizationTarget: "secret",
    summary: "Delete exact unbound Namespace-owned Secret material",
    tags: ["Secrets"],
    schema: {
      querystring: EmptyQuery,
      params: SecretParams,
      response: { 204: Type.Null(), ...mutationErrors },
    },
  },
  {
    operationId: "createServiceAccount",
    method: "POST",
    path: "/namespaces/:namespaceId/service-accounts",
    action: "openclaw.service_accounts.create",
    iamAction: "create",
    resourceKind: "service_account",
    authorizationTarget: "namespace_collection",
    summary: "Create a native Namespace-owned ServiceAccount",
    tags: ["Service accounts"],
    schema: {
      querystring: EmptyQuery,
      params: NamespaceParams,
      body: CreateServiceAccountBody,
      response: { 201: ServiceAccountResponse, ...createErrors },
    },
  },
  {
    operationId: "listServiceAccounts",
    method: "GET",
    path: "/namespaces/:namespaceId/service-accounts",
    action: "openclaw.service_accounts.list",
    iamAction: "read",
    resourceKind: "service_account",
    authorizationTarget: "namespace_and_service_account_candidates",
    summary: "List authorized Namespace-owned ServiceAccounts in one exact Namespace",
    tags: ["Service accounts"],
    schema: {
      querystring: EmptyQuery,
      params: NamespaceParams,
      response: { 200: ServiceAccountListResponse, ...readErrors },
    },
  },
  {
    operationId: "getServiceAccount",
    method: "GET",
    path: "/namespaces/:namespaceId/service-accounts/:serviceAccountId",
    action: "openclaw.service_accounts.read",
    iamAction: "read",
    resourceKind: "service_account",
    authorizationTarget: "service_account",
    summary: "Get an exact Namespace-owned ServiceAccount",
    tags: ["Service accounts"],
    schema: {
      querystring: EmptyQuery,
      params: ServiceAccountParams,
      response: { 200: ServiceAccountResponse, ...readErrors },
    },
  },
  {
    operationId: "createServiceAccountCredential",
    method: "POST",
    path: "/namespaces/:namespaceId/service-accounts/:serviceAccountId/credentials",
    action: "openclaw.service_accounts.credentials.create",
    iamAction: "update",
    resourceKind: "service_account",
    authorizationTarget: "service_account",
    summary: "Issue a managed credential for an exact Namespace-owned ServiceAccount",
    tags: ["Service accounts"],
    schema: {
      querystring: EmptyQuery,
      params: ServiceAccountParams,
      body: CreateServiceAccountCredentialBody,
      response: { 201: ServiceAccountResponse, ...createErrors },
    },
  },
  {
    operationId: "updateServiceAccountCredential",
    method: "PATCH",
    path: "/namespaces/:namespaceId/service-accounts/:serviceAccountId/credential",
    action: "openclaw.service_accounts.update",
    iamAction: "update",
    resourceKind: "service_account",
    authorizationTarget: "service_account",
    summary: "Associate an exact Namespace-local credential reference with a ServiceAccount",
    tags: ["Service accounts"],
    schema: {
      querystring: EmptyQuery,
      params: ServiceAccountParams,
      body: UpdateServiceAccountCredentialBody,
      response: { 200: ServiceAccountResponse, ...createErrors },
    },
  },
  {
    operationId: "deleteServiceAccount",
    method: "DELETE",
    path: "/namespaces/:namespaceId/service-accounts/:serviceAccountId",
    action: "openclaw.service_accounts.delete",
    iamAction: "delete",
    resourceKind: "service_account",
    authorizationTarget: "service_account",
    summary: "Delete an exact unreferenced Namespace-owned ServiceAccount",
    tags: ["Service accounts"],
    schema: {
      querystring: EmptyQuery,
      params: ServiceAccountParams,
      response: { 204: Type.Null(), ...mutationErrors },
    },
  },
  {
    operationId: "createAgent",
    method: "POST",
    path: "/namespaces/:namespaceId/agents",
    action: "openclaw.agents.create",
    iamAction: "create",
    resourceKind: "agent",
    authorizationTarget: "namespace_collection",
    summary: "Create a Namespace-owned Agent",
    tags: ["Agents"],
    schema: {
      querystring: EmptyQuery,
      params: NamespaceParams,
      body: CreateAgentBody,
      response: { 201: AgentResponse, ...createErrors },
    },
  },
  {
    operationId: "updateAgent",
    method: "PATCH",
    path: "/namespaces/:namespaceId/agents/:agentId",
    action: "openclaw.agents.update",
    iamAction: "update",
    resourceKind: "agent",
    authorizationTarget: "agent",
    summary: "Replace an exact Namespace-owned Agent's editable draft",
    tags: ["Agents"],
    schema: {
      querystring: EmptyQuery,
      params: AgentParams,
      body: UpdateAgentBody,
      response: { 200: AgentResponse, ...createErrors },
    },
  },
  {
    operationId: "listAgents",
    method: "GET",
    path: "/namespaces/:namespaceId/agents",
    action: "openclaw.agents.list",
    iamAction: "read",
    resourceKind: "agent",
    authorizationTarget: "namespace_and_agent_candidates",
    summary: "List authorized Agents in one exact Namespace",
    tags: ["Agents"],
    schema: {
      querystring: EmptyQuery,
      params: NamespaceParams,
      response: { 200: AgentListResponse, ...readErrors },
    },
  },
  {
    operationId: "getAgent",
    method: "GET",
    path: "/namespaces/:namespaceId/agents/:agentId",
    action: "openclaw.agents.read",
    iamAction: "read",
    resourceKind: "agent",
    authorizationTarget: "agent",
    summary: "Get an exact Namespace-owned Agent",
    tags: ["Agents"],
    schema: {
      querystring: EmptyQuery,
      params: AgentParams,
      response: { 200: AgentResponse, ...readErrors },
    },
  },
  {
    operationId: "getAgentRuntimeCredentials",
    method: "GET",
    path: "/namespaces/:namespaceId/agents/:agentId/runtime-credentials",
    action: "openclaw.agents.runtime_credentials.read",
    iamAction: "read",
    resourceKind: "agent",
    authorizationTarget: "agent",
    summary: "Get metadata for one Agent's provisioned runtime credentials",
    tags: ["Agents"],
    schema: {
      querystring: EmptyQuery,
      params: AgentParams,
      response: { 200: AgentRuntimeCredentialResponse, ...readErrors },
    },
  },
  {
    operationId: "provisionAgentRuntimeCredentials",
    method: "POST",
    path: "/namespaces/:namespaceId/agents/:agentId/runtime-credentials",
    action: "openclaw.agents.runtime_credentials.provision",
    iamAction: "operate",
    resourceKind: "agent",
    authorizationTarget: "agent",
    summary: "Provision initial runtime credentials for one undeployed Agent",
    tags: ["Agents"],
    schema: {
      querystring: EmptyQuery,
      params: AgentParams,
      body: AgentRuntimeCredentialsBody,
      response: { 200: AgentRuntimeCredentialResponse, ...createErrors },
    },
  },
  {
    operationId: "deployAgent",
    method: "POST",
    path: "/namespaces/:namespaceId/agents/:agentId/deploy",
    action: "openclaw.agents.deploy",
    iamAction: "deploy",
    resourceKind: "agent",
    authorizationTarget: "agent",
    summary: "Admit an immutable revision from the Agent's saved draft",
    tags: ["Agents"],
    schema: {
      querystring: EmptyQuery,
      params: AgentParams,
      response: { 202: AgentRevisionResponse, ...mutationErrors },
    },
  },
  {
    operationId: "getAgentWorkspaceFile",
    method: "GET",
    path: "/namespaces/:namespaceId/agents/:agentId/workspace/files/:name",
    action: "openclaw.agents.workspace.files.read",
    iamAction: "read",
    resourceKind: "agent",
    authorizationTarget: "agent",
    summary: "Read an allowed workspace file from one active Agent",
    tags: ["Agents"],
    schema: {
      querystring: EmptyQuery,
      params: WorkspaceFileParams,
      response: { 200: WorkspaceFileResponse, ...readErrors },
    },
  },
  {
    operationId: "putAgentWorkspaceFile",
    method: "PUT",
    path: "/namespaces/:namespaceId/agents/:agentId/workspace/files/:name",
    action: "openclaw.agents.workspace.files.write",
    iamAction: "operate",
    resourceKind: "agent",
    authorizationTarget: "agent",
    summary: "Create or replace an allowed workspace file for one active Agent",
    tags: ["Agents"],
    schema: {
      querystring: EmptyQuery,
      params: WorkspaceFileParams,
      body: UpdateWorkspaceFileBody,
      response: { 200: WorkspaceFileUpdateResponse, ...createErrors },
    },
  },
  {
    operationId: "listAgentRevisions",
    method: "GET",
    path: "/namespaces/:namespaceId/agents/:agentId/revisions",
    action: "openclaw.agent_revisions.list",
    iamAction: "read",
    resourceKind: "agent",
    authorizationTarget: "agent_collection",
    summary: "List authorized immutable revisions for one exact Agent",
    tags: ["Agent revisions"],
    schema: {
      querystring: EmptyQuery,
      params: AgentParams,
      response: { 200: AgentRevisionListResponse, ...readErrors },
    },
  },
  {
    operationId: "getAgentRevision",
    method: "GET",
    path: "/namespaces/:namespaceId/agents/:agentId/revisions/:revisionId",
    action: "openclaw.agent_revisions.read",
    iamAction: "read",
    resourceKind: "agent_revision",
    authorizationTarget: "requested_revision",
    summary: "Get an exact authorized immutable Agent revision",
    tags: ["Agent revisions"],
    schema: {
      querystring: EmptyQuery,
      params: RevisionParams,
      response: { 200: AgentRevisionResponse, ...readErrors },
    },
  },
] as const;

export type OccApiRoute = (typeof occApiRoutes)[number];
export type OccApiOperationId = OccApiRoute["operationId"];
